(function(g){var window=this;var g6=function(a){g.zH.call(this,{I:"div",M:"ytp-miniplayer-ui"});this.player=a;this.K=!1;this.J=this.F=this.C=void 0;this.R(a,"minimized",this.bU);this.R(a,"onStateChange",this.uX)},h6=function(a){g.DU.call(this,a);
this.o=new g6(this.player);this.o.hide();g.tU(this.player,this.o.element,4);a.app.L.o&&(this.load(),g.U(a.getRootNode(),"ytp-player-minimized",!0))};
g.r(g6,g.zH);g.h=g6.prototype;
g.h.show=function(){this.C=new g.iu(this.rQ,null,this);this.C.start();if(!this.K){this.H=new g.NZ(this.player,this);g.N(this,this.H);g.tU(this.player,this.H.element,4);this.H.F=.6;this.P=new g.lZ(this.player);g.N(this,this.P);this.G=new g.W({I:"div",M:"ytp-miniplayer-scrim"});g.N(this,this.G);this.G.xa(this.element);this.R(this.G.element,"click",this.FE);var a=new g.W({I:"button",ea:["ytp-miniplayer-close-button","ytp-button"],U:{"aria-label":"Kapat"},O:[g.YU()]});g.N(this,a);a.xa(this.G.element);
this.R(a.element,"click",this.XC);this.D=new g.W({I:"div",M:"ytp-miniplayer-controls"});g.N(this,this.D);this.D.xa(this.G.element);this.R(this.D.element,"click",this.FE);var b=new g.W({I:"div",M:"ytp-miniplayer-button-container"});g.N(this,b);b.xa(this.D.element);a=new g.W({I:"div",M:"ytp-miniplayer-play-button-container"});g.N(this,a);a.xa(this.D.element);var c=new g.W({I:"div",M:"ytp-miniplayer-button-container"});g.N(this,c);c.xa(this.D.element);this.N=new g.lY(this.player,this,!1);g.N(this,this.N);
this.N.xa(b.element);b=new g.jY(this.player,this);g.N(this,b);b.xa(a.element);this.L=new g.lY(this.player,this,!0);g.N(this,this.L);this.L.xa(c.element);this.J=new g.ZY(this.player,this);g.N(this,this.J);this.J.xa(this.G.element);this.F=new g.mY(this.player,this);g.N(this,this.F);g.tU(this.player,this.F.element,4);this.B=new g.W({I:"div",M:"ytp-miniplayer-buttons"});g.N(this,this.B);g.tU(this.player,this.B.element,4);this.B.hide();a=new g.W({I:"button",ea:["ytp-miniplayer-close-button","ytp-button"],
U:{"aria-label":"Kapat"},O:[g.YU()]});g.N(this,a);a.xa(this.B.element);this.R(a.element,"click",this.XC);a=new g.W({I:"button",ea:["ytp-miniplayer-replay-button","ytp-button"],U:{"aria-label":"Kapat"},O:[g.ZU()]});g.N(this,a);a.xa(this.B.element);this.R(a.element,"click",this.dV);this.R(this.player,"presentingplayerstatechange",this.sQ);this.R(this.player,"appresize",this.Iv);this.R(this.player,"fullscreentoggled",this.Iv);this.Iv();this.K=!0}0!=this.player.mi()&&g.zH.prototype.show.call(this);this.F.show();
this.player.mn("annotations_module")};
g.h.hide=function(){this.C&&(this.C.dispose(),this.C=void 0);g.zH.prototype.hide.call(this);this.player.app.L.o||(this.K&&this.F.hide(),this.player.Wk("annotations_module"))};
g.h.X=function(){this.C&&(this.C.dispose(),this.C=void 0);g.zH.prototype.X.call(this)};
g.h.XC=function(){this.player.Wd();this.player.ya("onCloseMiniplayer")};
g.h.dV=function(){this.player.ad()};
g.h.FE=function(a){if(a.target==this.G.element||a.target==this.D.element)g.YD("kevlar_miniplayer_scrim_pause")?2==this.player.mi()?this.player.ad():this.player.nd():this.player.ya("onExpandMiniplayer")};
g.h.bU=function(){g.U(this.player.getRootNode(),"ytp-player-minimized",this.player.app.L.o);this.player.app.L.o&&0==this.player.mi()?this.B.show():this.B.hide()};
g.h.rQ=function(){g.vta(this.F);this.J.C();this.C.start()};
g.h.sQ=function(a){g.X(a.state,32)&&this.H.hide()};
g.h.Iv=function(){var a=this.F,b=g.$T(this.player).Ua().width;a.Na=0;a.F=b;a.H=!1;g.oY(a)};
g.h.uX=function(a){this.player.app.L.o&&(0==a?(this.hide(),this.B.show()):(this.show(),this.B.hide()))};
g.h.Ob=function(){return this.H};
g.h.md=function(){return!1};
g.h.Jk=function(){return!1};
g.h.UF=function(){};
g.h.Vo=function(){};
g.h.Wo=function(){};
g.h.un=function(){return null};
g.h.Gv=function(){return new g.hh(0,0,0,0)};
g.h.Hv=function(){};
g.h.Hq=function(a,b,c){a.style.left="";a.style.top="";a.style.bottom="";var d=g.Ph(a),e=g.$T(this.player).Ua().width;b&&["ytp-prev-button","ytp-next-button"].some(function(a){return g.yq(b,a)})?(c=12,a.style.top="12px"):(c-=d.width/2,a.style.bottom="25px");
a.style.left=g.kd(c,0,e-d.width)+"px"};
g.h.pq=function(){};
g.h.Jv=function(){};g.r(h6,g.DU);h6.prototype.init=function(){};
h6.prototype.load=function(){this.player.KC();this.o.show()};
h6.prototype.unload=function(){this.player.MC();this.o.hide()};g.AX.miniplayer=h6;})(_yt_player);
